name: revealjs
author_email: gunag5127@gmail.com
version: 0.0.8
description: Reveal.js Presentation Builder Inspired By revealjs
long_description_content_type: text/markdown
author: guna
url: https://github.com/gunaNeelamegam/revealjs-presentation.git
