name: revealjs
author_email: gunag5127@gmail.com
version: 0.0.3
description: Reveal.js Presentation
long_description_content_type: text/markdown
author: guna
url: https://github.com/gunaNeelamegam/revealjs-presentation.git
